export const ANCHORS = {
  hero: 'hero',
  advantages: 'advantages',
  howItWorks: 'how-it-works',
  schedule: 'schedule',
  compare: 'compare',
  pricing: 'pricing',
  ukraine: 'ukraine',
  faq: 'faq',
  cta: 'cta',
  cefr: 'cefr',
  flow: 'flow',
  coinLoop: 'coin-loop',
  coinEconomics: 'coin-economics',
  smart: 'smart',
  privacy: 'privacy',
  plans: 'plans',
} as const;
